[theme]
  # ==== Replace these with your exact Solidus brand colors ====
  primaryColor = "#0f181b"  
  backgroundColor = "#EEF0F4" 
  secondaryBackgroundColor = "#FFCD26"
  textColor = "#003165"  
  font = "sans serif" 

[server]
  headless = true
  enableCORS = false
